# Generated by Django 4.1.6 on 2023-02-23 20:52

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatars/%Y/%m/%d', validators=[account.models.size_validator]),
        ),
    ]
